language: go
go:
  - "1.11"
git:
  depth: 1
before_install:
  - go get github.com/GodlikePenguin/agogos-datatypes
script:
  - ./build.sh
  - docker push edwarddobson/agogos-proxy:$(git rev-parse --short HEAD)